language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mechanikhil/react-test ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mechanikhil/react-test npm test

after_success:
  - docker build -t mechanikhil/multi-client ./client
  - docker build -t mechanikhil/multi-nginx ./nginx
  - docker build -t mechanikhil/multi-servier ./server
  - docker build -t mechanikhil/multi-worker ./worker
# Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push to docker hub
  - docker push mechanikhil/multi-client
  - docker push mechanikhil/multi-nginx
  - docker push mechanikhil/multi-server
  - docker push mechanikhil/multi-worker