language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mechanikhil/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mechanikhil/react-test npm test

after_success:
  - docker build -t mechanikhil/multi-client ./client
  - docker build -t mechanikhil/multi-nginx ./nginx
  - docker build -t mechanikhil/multi-server ./server
  - docker build -t mechanikhil/multi-worker ./worker
# Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push to docker hub
  - docker push mechanikhil/multi-client
  - docker push mechanikhil/multi-nginx
  - docker push mechanikhil/multi-server
  - docker push mechanikhil/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-907087174207'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY